# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6f4125fb6b549386d4da9e8b661b436fabb8f3ffe0226fe26b183fe12cf9b95b65db35c2fea6254128977cacfdcc40ba423bc75b6496888240c4d056832a9d2

test:
  secret_key_base: c785754540add63151c8fecd5e14115dc5e156925b55f43d0740d414aab2ba759cb02b0da366a139f11d89f05d353285a31acfe7ec70b7c631209acd15f47f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
